/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sky.gradle20;

import celcord.jaxb.ReadXmlDemo2;
import celcord.jaxb.Root2;
import org.junit.Test;

import static celcord.jaxb.ReadXmlDemo2.xmlStrToObj;
import static org.junit.Assert.*;

public class ReadXmlTest{
    static final String srcXML = "xml/outnewschema.stars.xml";
    @Test public void doReadXmlTest() {
        celcord.jaxb.ReadXmlDemo2 classUnderTest = new celcord.jaxb.ReadXmlDemo2();
        ReadXmlDemo2.Log.d("gg", "testing abcd");
        assertTrue("this is assert: ",  1 == 1);
		/* */
	    // test xmlStrToClassInstance
		Root2.SkyobjColl root2List = xmlStrToObj(Root2.SkyobjColl.class, classUnderTest.fileToString(srcXML));
		String outpt = "";  int ct = 0;
		for (Root2.Skyobj skyObj : root2List.getSkyObjList()) {
			outpt += ct++ + "..: " + skyObj.getName() + "/" + skyObj.getMessier_num() + "/" + skyObj.getDecl() + ", ";}
		ReadXmlDemo2.Log.d("gg", "testing xmlStrToClassInstance... " + root2List.getSkyObjList().size() + "\n" + outpt);
        assertTrue("testing for 'Rigil Kent' in output: ", outpt.contains("Rigil Kent"));
    }
}
